// flow-typed signature: 33b5f1f7c2f4fa421030d6eb353e38fb
// flow-typed version: <<STUB>>/immutadot_v^0.1.11/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutadot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutadot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immutadot/array/index' {
  declare module.exports: any;
}

declare module 'immutadot/array/push' {
  declare module.exports: any;
}

declare module 'immutadot/array/push.spec' {
  declare module.exports: any;
}

declare module 'immutadot/array/xor' {
  declare module.exports: any;
}

declare module 'immutadot/array/xor.spec' {
  declare module.exports: any;
}

declare module 'immutadot/collection/index' {
  declare module.exports: any;
}

declare module 'immutadot/collection/map' {
  declare module.exports: any;
}

declare module 'immutadot/collection/map.spec' {
  declare module.exports: any;
}

declare module 'immutadot/core/consts' {
  declare module.exports: any;
}

declare module 'immutadot/core/index' {
  declare module.exports: any;
}

declare module 'immutadot/core/set' {
  declare module.exports: any;
}

declare module 'immutadot/core/set.spec' {
  declare module.exports: any;
}

declare module 'immutadot/core/unset' {
  declare module.exports: any;
}

declare module 'immutadot/core/unset.spec' {
  declare module.exports: any;
}

declare module 'immutadot/core/update' {
  declare module.exports: any;
}

declare module 'immutadot/core/update.spec' {
  declare module.exports: any;
}

declare module 'immutadot/lang/index' {
  declare module.exports: any;
}

declare module 'immutadot/lang/toggle' {
  declare module.exports: any;
}

declare module 'immutadot/lang/toggle.spec' {
  declare module.exports: any;
}

declare module 'immutadot/math/add' {
  declare module.exports: any;
}

declare module 'immutadot/math/add.spec' {
  declare module.exports: any;
}

declare module 'immutadot/math/index' {
  declare module.exports: any;
}

declare module 'immutadot/seq/chain' {
  declare module.exports: any;
}

declare module 'immutadot/seq/chain.spec' {
  declare module.exports: any;
}

declare module 'immutadot/seq/ChainWrapper' {
  declare module.exports: any;
}

declare module 'immutadot/seq/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immutadot/array/index.js' {
  declare module.exports: $Exports<'immutadot/array/index'>;
}
declare module 'immutadot/array/push.js' {
  declare module.exports: $Exports<'immutadot/array/push'>;
}
declare module 'immutadot/array/push.spec.js' {
  declare module.exports: $Exports<'immutadot/array/push.spec'>;
}
declare module 'immutadot/array/xor.js' {
  declare module.exports: $Exports<'immutadot/array/xor'>;
}
declare module 'immutadot/array/xor.spec.js' {
  declare module.exports: $Exports<'immutadot/array/xor.spec'>;
}
declare module 'immutadot/collection/index.js' {
  declare module.exports: $Exports<'immutadot/collection/index'>;
}
declare module 'immutadot/collection/map.js' {
  declare module.exports: $Exports<'immutadot/collection/map'>;
}
declare module 'immutadot/collection/map.spec.js' {
  declare module.exports: $Exports<'immutadot/collection/map.spec'>;
}
declare module 'immutadot/core/consts.js' {
  declare module.exports: $Exports<'immutadot/core/consts'>;
}
declare module 'immutadot/core/index.js' {
  declare module.exports: $Exports<'immutadot/core/index'>;
}
declare module 'immutadot/core/set.js' {
  declare module.exports: $Exports<'immutadot/core/set'>;
}
declare module 'immutadot/core/set.spec.js' {
  declare module.exports: $Exports<'immutadot/core/set.spec'>;
}
declare module 'immutadot/core/unset.js' {
  declare module.exports: $Exports<'immutadot/core/unset'>;
}
declare module 'immutadot/core/unset.spec.js' {
  declare module.exports: $Exports<'immutadot/core/unset.spec'>;
}
declare module 'immutadot/core/update.js' {
  declare module.exports: $Exports<'immutadot/core/update'>;
}
declare module 'immutadot/core/update.spec.js' {
  declare module.exports: $Exports<'immutadot/core/update.spec'>;
}
declare module 'immutadot/index' {
  declare module.exports: $Exports<'immutadot'>;
}
declare module 'immutadot/index.js' {
  declare module.exports: $Exports<'immutadot'>;
}
declare module 'immutadot/lang/index.js' {
  declare module.exports: $Exports<'immutadot/lang/index'>;
}
declare module 'immutadot/lang/toggle.js' {
  declare module.exports: $Exports<'immutadot/lang/toggle'>;
}
declare module 'immutadot/lang/toggle.spec.js' {
  declare module.exports: $Exports<'immutadot/lang/toggle.spec'>;
}
declare module 'immutadot/math/add.js' {
  declare module.exports: $Exports<'immutadot/math/add'>;
}
declare module 'immutadot/math/add.spec.js' {
  declare module.exports: $Exports<'immutadot/math/add.spec'>;
}
declare module 'immutadot/math/index.js' {
  declare module.exports: $Exports<'immutadot/math/index'>;
}
declare module 'immutadot/seq/chain.js' {
  declare module.exports: $Exports<'immutadot/seq/chain'>;
}
declare module 'immutadot/seq/chain.spec.js' {
  declare module.exports: $Exports<'immutadot/seq/chain.spec'>;
}
declare module 'immutadot/seq/ChainWrapper.js' {
  declare module.exports: $Exports<'immutadot/seq/ChainWrapper'>;
}
declare module 'immutadot/seq/index.js' {
  declare module.exports: $Exports<'immutadot/seq/index'>;
}
