// flow-typed signature: 62ed27956fe7fa9c9f2b9979af425740
// flow-typed version: <<STUB>>/immutadot_v^0.2.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutadot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutadot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immutadot/array/concat' {
  declare module.exports: any;
}

declare module 'immutadot/array/convertArrayMethod' {
  declare module.exports: any;
}

declare module 'immutadot/array/difference' {
  declare module.exports: any;
}

declare module 'immutadot/array/drop' {
  declare module.exports: any;
}

declare module 'immutadot/array/index' {
  declare module.exports: any;
}

declare module 'immutadot/array/pull' {
  declare module.exports: any;
}

declare module 'immutadot/array/push' {
  declare module.exports: any;
}

declare module 'immutadot/array/remove' {
  declare module.exports: any;
}

declare module 'immutadot/array/splice' {
  declare module.exports: any;
}

declare module 'immutadot/array/unshift' {
  declare module.exports: any;
}

declare module 'immutadot/array/xor' {
  declare module.exports: any;
}

declare module 'immutadot/collection/index' {
  declare module.exports: any;
}

declare module 'immutadot/collection/map' {
  declare module.exports: any;
}

declare module 'immutadot/lang/index' {
  declare module.exports: any;
}

declare module 'immutadot/lang/toggle' {
  declare module.exports: any;
}

declare module 'immutadot/math/add' {
  declare module.exports: any;
}

declare module 'immutadot/math/index' {
  declare module.exports: any;
}

declare module 'immutadot/object/assign' {
  declare module.exports: any;
}

declare module 'immutadot/object/index' {
  declare module.exports: any;
}

declare module 'immutadot/object/mapValues' {
  declare module.exports: any;
}

declare module 'immutadot/object/pickBy' {
  declare module.exports: any;
}

declare module 'immutadot/object/set' {
  declare module.exports: any;
}

declare module 'immutadot/object/unset' {
  declare module.exports: any;
}

declare module 'immutadot/object/update' {
  declare module.exports: any;
}

declare module 'immutadot/seq/chain' {
  declare module.exports: any;
}

declare module 'immutadot/seq/ChainWrapper' {
  declare module.exports: any;
}

declare module 'immutadot/seq/index' {
  declare module.exports: any;
}

declare module 'immutadot/util/convert' {
  declare module.exports: any;
}

declare module 'immutadot/util/index' {
  declare module.exports: any;
}

declare module 'immutadot/util/lodashFpConvert' {
  declare module.exports: any;
}

declare module 'immutadot/util/using' {
  declare module.exports: any;
}

declare module 'immutadot/util/UsingWrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immutadot/array/concat.js' {
  declare module.exports: $Exports<'immutadot/array/concat'>;
}
declare module 'immutadot/array/convertArrayMethod.js' {
  declare module.exports: $Exports<'immutadot/array/convertArrayMethod'>;
}
declare module 'immutadot/array/difference.js' {
  declare module.exports: $Exports<'immutadot/array/difference'>;
}
declare module 'immutadot/array/drop.js' {
  declare module.exports: $Exports<'immutadot/array/drop'>;
}
declare module 'immutadot/array/index.js' {
  declare module.exports: $Exports<'immutadot/array/index'>;
}
declare module 'immutadot/array/pull.js' {
  declare module.exports: $Exports<'immutadot/array/pull'>;
}
declare module 'immutadot/array/push.js' {
  declare module.exports: $Exports<'immutadot/array/push'>;
}
declare module 'immutadot/array/remove.js' {
  declare module.exports: $Exports<'immutadot/array/remove'>;
}
declare module 'immutadot/array/splice.js' {
  declare module.exports: $Exports<'immutadot/array/splice'>;
}
declare module 'immutadot/array/unshift.js' {
  declare module.exports: $Exports<'immutadot/array/unshift'>;
}
declare module 'immutadot/array/xor.js' {
  declare module.exports: $Exports<'immutadot/array/xor'>;
}
declare module 'immutadot/collection/index.js' {
  declare module.exports: $Exports<'immutadot/collection/index'>;
}
declare module 'immutadot/collection/map.js' {
  declare module.exports: $Exports<'immutadot/collection/map'>;
}
declare module 'immutadot/index' {
  declare module.exports: $Exports<'immutadot'>;
}
declare module 'immutadot/index.js' {
  declare module.exports: $Exports<'immutadot'>;
}
declare module 'immutadot/lang/index.js' {
  declare module.exports: $Exports<'immutadot/lang/index'>;
}
declare module 'immutadot/lang/toggle.js' {
  declare module.exports: $Exports<'immutadot/lang/toggle'>;
}
declare module 'immutadot/math/add.js' {
  declare module.exports: $Exports<'immutadot/math/add'>;
}
declare module 'immutadot/math/index.js' {
  declare module.exports: $Exports<'immutadot/math/index'>;
}
declare module 'immutadot/object/assign.js' {
  declare module.exports: $Exports<'immutadot/object/assign'>;
}
declare module 'immutadot/object/index.js' {
  declare module.exports: $Exports<'immutadot/object/index'>;
}
declare module 'immutadot/object/mapValues.js' {
  declare module.exports: $Exports<'immutadot/object/mapValues'>;
}
declare module 'immutadot/object/pickBy.js' {
  declare module.exports: $Exports<'immutadot/object/pickBy'>;
}
declare module 'immutadot/object/set.js' {
  declare module.exports: $Exports<'immutadot/object/set'>;
}
declare module 'immutadot/object/unset.js' {
  declare module.exports: $Exports<'immutadot/object/unset'>;
}
declare module 'immutadot/object/update.js' {
  declare module.exports: $Exports<'immutadot/object/update'>;
}
declare module 'immutadot/seq/chain.js' {
  declare module.exports: $Exports<'immutadot/seq/chain'>;
}
declare module 'immutadot/seq/ChainWrapper.js' {
  declare module.exports: $Exports<'immutadot/seq/ChainWrapper'>;
}
declare module 'immutadot/seq/index.js' {
  declare module.exports: $Exports<'immutadot/seq/index'>;
}
declare module 'immutadot/util/convert.js' {
  declare module.exports: $Exports<'immutadot/util/convert'>;
}
declare module 'immutadot/util/index.js' {
  declare module.exports: $Exports<'immutadot/util/index'>;
}
declare module 'immutadot/util/lodashFpConvert.js' {
  declare module.exports: $Exports<'immutadot/util/lodashFpConvert'>;
}
declare module 'immutadot/util/using.js' {
  declare module.exports: $Exports<'immutadot/util/using'>;
}
declare module 'immutadot/util/UsingWrapper.js' {
  declare module.exports: $Exports<'immutadot/util/UsingWrapper'>;
}
