// flow-typed signature: 7f5ea305f0cfc7a21d8c774c8c31d65a
// flow-typed version: <<STUB>>/react-resizable_v1.7.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-resizable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-resizable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-resizable/build/cloneElement' {
  declare module.exports: any;
}

declare module 'react-resizable/build/Resizable' {
  declare module.exports: any;
}

declare module 'react-resizable/build/ResizableBox' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-resizable/build/cloneElement.js' {
  declare module.exports: $Exports<'react-resizable/build/cloneElement'>;
}
declare module 'react-resizable/build/Resizable.js' {
  declare module.exports: $Exports<'react-resizable/build/Resizable'>;
}
declare module 'react-resizable/build/ResizableBox.js' {
  declare module.exports: $Exports<'react-resizable/build/ResizableBox'>;
}
declare module 'react-resizable/index' {
  declare module.exports: $Exports<'react-resizable'>;
}
declare module 'react-resizable/index.js' {
  declare module.exports: $Exports<'react-resizable'>;
}
