// flow-typed signature: 2cbb1050da2268afd13a175a84a2d8ad
// flow-typed version: <<STUB>>/react-toolbox-themr_v^1.0.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toolbox-themr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toolbox-themr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toolbox-themr/bin/builder' {
  declare module.exports: any;
}

declare module 'react-toolbox-themr/src/__tests__/configure.test' {
  declare module.exports: any;
}

declare module 'react-toolbox-themr/src/__tests__/getAllDependencies.test' {
  declare module.exports: any;
}

declare module 'react-toolbox-themr/src/__tests__/getDependencies.test' {
  declare module.exports: any;
}

declare module 'react-toolbox-themr/src/__tests__/getPath.test' {
  declare module.exports: any;
}

declare module 'react-toolbox-themr/src/configure' {
  declare module.exports: any;
}

declare module 'react-toolbox-themr/src/constants' {
  declare module.exports: any;
}

declare module 'react-toolbox-themr/src/getAllDependencies' {
  declare module.exports: any;
}

declare module 'react-toolbox-themr/src/getDependencies' {
  declare module.exports: any;
}

declare module 'react-toolbox-themr/src/getPath' {
  declare module.exports: any;
}

declare module 'react-toolbox-themr/src/postcss' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toolbox-themr/bin/builder.js' {
  declare module.exports: $Exports<'react-toolbox-themr/bin/builder'>;
}
declare module 'react-toolbox-themr/index' {
  declare module.exports: $Exports<'react-toolbox-themr'>;
}
declare module 'react-toolbox-themr/index.js' {
  declare module.exports: $Exports<'react-toolbox-themr'>;
}
declare module 'react-toolbox-themr/src/__tests__/configure.test.js' {
  declare module.exports: $Exports<'react-toolbox-themr/src/__tests__/configure.test'>;
}
declare module 'react-toolbox-themr/src/__tests__/getAllDependencies.test.js' {
  declare module.exports: $Exports<'react-toolbox-themr/src/__tests__/getAllDependencies.test'>;
}
declare module 'react-toolbox-themr/src/__tests__/getDependencies.test.js' {
  declare module.exports: $Exports<'react-toolbox-themr/src/__tests__/getDependencies.test'>;
}
declare module 'react-toolbox-themr/src/__tests__/getPath.test.js' {
  declare module.exports: $Exports<'react-toolbox-themr/src/__tests__/getPath.test'>;
}
declare module 'react-toolbox-themr/src/configure.js' {
  declare module.exports: $Exports<'react-toolbox-themr/src/configure'>;
}
declare module 'react-toolbox-themr/src/constants.js' {
  declare module.exports: $Exports<'react-toolbox-themr/src/constants'>;
}
declare module 'react-toolbox-themr/src/getAllDependencies.js' {
  declare module.exports: $Exports<'react-toolbox-themr/src/getAllDependencies'>;
}
declare module 'react-toolbox-themr/src/getDependencies.js' {
  declare module.exports: $Exports<'react-toolbox-themr/src/getDependencies'>;
}
declare module 'react-toolbox-themr/src/getPath.js' {
  declare module.exports: $Exports<'react-toolbox-themr/src/getPath'>;
}
declare module 'react-toolbox-themr/src/postcss.js' {
  declare module.exports: $Exports<'react-toolbox-themr/src/postcss'>;
}
